### ISSUE TITLE
navLinks - TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by Luiz-Otavio-Dorigon** [fullcalendar/fullcalendar-angular#255]
I added the property **[navLinks] = true** and on clicking the following error occurs.

<img width="513" alt="Captura de Tela 2019-11-22 às 17 16 52" src="https://user-images.githubusercontent.com/4552539/69457545-0faea200-0d4c-11ea-9c5e-94b5b9e6cdd2.png">

**Comment by azebich** [comment]
Hi,

I've found that this problem happens because in the node_modules/@fullcalendar/angular/fesm2015/fullcalendar-angular.js file the properties 'navLinkDayClick' and 'navLinkWeekClick' are in the OUTPUT_NAMES array and for the FullCalendarComponent.propDecorators object those properties are declared as [{ type: input }]. If I move the properties to the INPUT_NAMES array then everything works fine.

It could be connected to this fix https://github.com/fullcalendar/fullcalendar-angular/issues/220

**Comment by constantinoschristoforou** [comment]
Hello,

Any update on this?

**Comment by cscheffel** [comment]
I tapped into the same problem

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

`navLinks` seems to work fine now:

https://codesandbox.io/s/exciting-pasteur-tkw0x

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
