### ISSUE TITLE
EventInput does not work correctly

### ISSUE THREAD

**Issue by ARoshanZamir** [fullcalendar/fullcalendar-angular#265]
if you set the start property to `"2019-12-11T23:01:00"`

`{ title: "Event Title", start: "2019-12-11T23:01:00" }`

result will be like the following :
![eventinput](https://user-images.githubusercontent.com/4233035/70600117-d2209480-1be6-11ea-909b-8785199740a2.PNG)

if you set the start time to '23:01:00' .... '23:59:00' result is the same 

Why, Where I'm wrong ? 

[**Stackblitz Here**](https://stackblitz.com/edit/angular-wcgatr) ....

**Comment by alishmki** [comment]
I have the same problem , I'm stuck , remove this issue..

**Comment by jolle-c** [comment]
This is all according to expected behaviour.

If you don’t set an end time the default duration will kick in. It is set to 1 hour. Starting an event at 23.01 will end it 00.01 the following day. Thus it will, in month view, appear to span two days. The following day will only host one minute of the event and that will make it not visible when viewed in week view.

You can set a default duration to less than an hour
https://fullcalendar.io/docs/defaultTimedEventDuration

Or you can set an end time to something less than an hour

    { title: "Event Title", start: "2019-12-11T23:00:00", end: "2019-12-11T23:59:00” }


There is nothing fix here but your own code.

HDB
Jolle

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

It appears the issue was in the Stackblitz by setting the `end` time.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
