### ISSUE TITLE
Error: Failed to find '@fullcalendar/core/main.css'

### ISSUE THREAD

**Issue by tonedeafcoder** [fullcalendar/fullcalendar-angular#337]
Hello There,

I've added full calendar in my Angular 9 application and I get (1) this error. I have installed @fullcalendar(day, grid,  timegrid, interaction,core,angular and bootstrap) as you can see in (2) here. I could suppress the error to a warning(3) by creating an empty file(4) here
![1-Error](https://user-images.githubusercontent.com/68946863/90253819-6bcbd000-de5f-11ea-9440-da39449059ec.png)
![2-Package-json](https://user-images.githubusercontent.com/68946863/90253826-6d959380-de5f-11ea-977e-861acb976489.png)
![3-Warning](https://user-images.githubusercontent.com/68946863/90253829-6e2e2a00-de5f-11ea-8c49-54fd3c6d7488.png)
![4-file](https://user-images.githubusercontent.com/68946863/90253830-6ec6c080-de5f-11ea-8a1c-37edf4156669.png)

. Could anyone help me here.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue? Would really appreciate it because the time saved reproducing will be time spent fixing.

You can use the example project as a starting point: 

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular
