### ISSUE TITLE
Doesn´t work with angular 12 production build

### ISSUE THREAD

**Issue by CodeCakePie** [fullcalendar/fullcalendar-angular#372]
I´ve just updated to angular 12, and everything seems to work fine, but when making a production build of the application, it has a runtime error:

```
ERROR TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at nA (main.js:1)
    at $S (main.js:1)
    at sA (main.js:1)
    at $S (main.js:1)
    at sA (main.js:1)
    at fA (main.js:1)
    at flushToDom (main.js:1)
    at e.i.handleRenderRequest [as drainedOption] (main.js:1)
    at e.drained (main.js:1)
    at e.tryDrain (main.js:1)
```

I have tried it with the simple tutorial of how to use this component.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue? Would really appreciate it because the time saved reproducing will be time spent fixing.

You can use the example project as a starting point:

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular
